export const lang = {
  en: {
    search: "Search",
    searchPlaceholder: "What Would You Like To Watch Today?",
    signOut: "SignOut",
    title: "Shōgun",
    overview:
      "IN JAPAN IN THE YEAR 1600, AT THE DAWN OF A CENTURY-DEFINING CIVIL WAR, LORD YOSHII TORANAGA IS FIGHTING FOR HIS LIFE AS HIS ENEMIES ON THE COUNCIL OF REGENTS UNITE AGAINST HIM, WHEN A MYSTERIOUS EUROPEAN SHIP IS FOUND MAROONED IN A NEARBY FISHING VILLAGE",
    play: "Play",
    moreInfo: "More Info",
    trendingSeries: "Trending Series",
    trendingMovies: "Trending Movies",
    topRatedMovies: "Top Rated Movies",
    topRatedSeries: "Top Rated Series",
    english: "English",
    japanese: "Japanese",
    marathi: "Marathi",

    home: "Home",
  },
  ja: {
    search: "検索",
    searchPlaceholder: "今日は何を見たいですか?",
    signOut: "サインアウト",
    title: "将軍",
    overview:
      "1600年の日本、一世紀を決定づけた内戦の黎明期、吉井虎長公は摂政会議の敵が結束して命がけで戦っていたとき、謎のヨーロッパ船が近くの漁場で取り残されているのが発見された。村",
    play: "遊ぶ",
    moreInfo: "より詳しい情報",
    trendingSeries: "トレンドシリーズ",
    trendingMovies: "話題の映画",
    topRatedMovies: "最高評価の映画",
    topRatedSeries: "最高評価のシリーズ",
    english: "英語",
    japanese: "日本語",
    marathi: "マラーティー語",
    home: "ホームページ",
  },
  ma: {
    search: "शोधा",
    searchPlaceholder: "तुम्हाला आज काय बघायला आवडेल?",
    signOut: "साइन आउट",
    title: "शोगुन",
    overview:
      "1600 साली जपानमध्ये, एका शताब्दी-परिभाषित गृहयुद्धाच्या पहाटे, लॉर्ड योशी तोरनागा हे आपल्या जीवनासाठी रीजेंट्स अयुनिगियन्स कौन्सिलमध्ये लढत आहेत जवळच्या मासेमारीत सापडले गाव",
    play: "प्ले",
    moreInfo: "अधिक माहिती",
    trendingSeries: "ट्रेंडिंग मालिका",
    trendingMovies: "ट्रेंडिंग चित्रपट",
    topRatedMovies: "शीर्ष रेट केलेले चित्रपट",
    topRatedSeries: "शीर्ष रेटेड मालिका",
    english: "इंग्रजी",
    japanese: "जपानी",
    marathi: "मराठी",
    home: "मुख्यपृष्ठ",
  },
};
